import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import styles from "./layout.module.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.body}`}>

        <header className={styles.header}>
          <h1>Next Megamix 240426</h1>

          <nav>
            <Link href={'/'}>Home</Link>
            <Link href={'/cookies'}>Cookies</Link>
            <Link href={'/todos'}>Todos</Link>
            <Link href={'/events'}>Events</Link>
          </nav>
        </header>

        <main className={styles.main}>
          {children}
        </main>

        <footer className={styles.footer}>
          <p>&copy; 2024</p>
        </footer>


      </body>
    </html>
  );
}
